# User Settings | Edit there as per required

title: "Brendan Ashworth"
url: "http://blog.ashworth.in"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    Brendan Ashworth <span class="faded">'s blog</span>

email: brendan.ashworth@me.com
author: Brendan Ashworth
# This description will show up in google search results
# (for index page) etc.
description: >
    Personal blog of my [lack of] experience in life.
    Business, technology, and various ramblings.

# This will what will show against &copy; in the footer
copyright: " Brendan Ashworth 2018"
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro

# Comments are powered by disqus
comments: false

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    I'm a student, located where technology and business intersect.

about_footer: false

twitter_username: brendanash_
github_username: brendanashworth

favicon: false

paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-53226403-1 # GA Tracking ID

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

plugins:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
